spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/postpartum_tracker
spring.datasource.username=jesicasarah
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
